version: '3.8'

services:
  # Servicio PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comisiones_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../backend:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - comisiones_network
    depends_on:
      - db

  # Servicio Nginx
  nginx:
    image: nginx:alpine
    container_name: comisiones_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ../backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - comisiones_network
    depends_on:
      - app

  # Servicio MySQL
  db:
    image: mysql:8.0
    container_name: comisiones_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: comisiones_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: comisiones_user
      MYSQL_PASSWORD: comisiones_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ../backend/database/migrations:/docker-entrypoint-initdb.d
    networks:
      - comisiones_network

  # Servicio phpMyAdmin (opcional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: comisiones_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8081:80"
    networks:
      - comisiones_network
    depends_on:
      - db

  # Servicio para Frontend (desarrollo)
  frontend:
    image: node:18-alpine
    container_name: comisiones_frontend
    working_dir: /app
    volumes:
      - ../frontend:/app
    ports:
      - "4200:4200"
    command: npm start
    networks:
      - comisiones_network

networks:
  comisiones_network:
    driver: bridge

volumes:
  db_data:
    driver: local